# Generated by Django 3.1.5 on 2021-01-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autrhor',
            new_name='author',
        ),
    ]
